desafioae:
  outputs:
    dev:
      dataset: dev_lineker
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: service-account
      priority: interactive
      project: desafioae
      threads: 4
      type: bigquery
  target: dev